{
    "source": "BDSA",
    "name": "BDSA-2020-3598",
    "title": "Cloud Foundry CAPI Vulnerable to Information Exposure via Incorrect Permission Assignment in Droplets",
    "description": "Cloud Foundry CAPI (Cloud Controller) contains an information exposure vulnerability. This is due to an incorrect permissions issue when listing droplets from spaces. An authenticated attacker with `cloud_controller.read` access, but no access in any spaces, is able to list all droplets in all spaces.",
    "technicalDescription": "",
    "publishedDate": "2020-12-01T15:18:18.631Z",
    "updatedDate": "2020-12-01T15:18:18.623Z",
    "disclosureDate": "2020-09-01T00:00:00.000Z",
    "solution": "Fixed in CAPI [**1.98.0**](https://github.com/cloudfoundry/capi-release/releases/tag/1.98.0). \n\nFixed in CF Deployment [**13.17.0**](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.17.0).",
    "severity": "LOW",
    "cvss2": {
        "baseScore": 4.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 8.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "SINGLE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.0
        },
        "vector": "(AV:N/AC:L/Au:S/C:P/I:N/A:N/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 4.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 2.8,
        "severity": "LOW",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "LOW",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.8
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2020-08-28T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 3.8,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3598",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-863"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-5418",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3598/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/cloudfoundry/capi-release/releases/tag/1.98.0",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.17.0",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://www.cloudfoundry.org/blog/cve-2020-5418/",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3598/default-remediation-status"
            }
        ]
    }
}