{
    "source": "BDSA",
    "name": "BDSA-2021-1512",
    "title": "Pillow Vulnerable to Denial-of-Service (DoS) via Resource Exhaustion in 'EpsImagePlugin.py' File",
    "description": "Python Pillow Library is vulnerable to a denial-of-service (DoS) condition. Attackers can target applications using this library to process untrusted image files, and trigger an application crash.",
    "technicalDescription": "The DoS is due to an possible resource exhaustion occurring in the `readLine` function in `src/PIL/EpsImagePlugin.py`.  A crafted `EPS` file can be used to cause the pillow library to consume memory and potentially hang the application or cause a crash. \n\nThis issue is due to the `readLine` function not checking the length of data when reading a `EPS` file until a line end character. The line data was then added in a quadratic manner and could be read again. If the length of data is `0` the function will enter a state of infinite loop.",
    "publishedDate": "2021-05-21T10:21:48.622Z",
    "updatedDate": "2021-05-21T10:24:51.830Z",
    "disclosureDate": "2021-04-01T00:00:00.000Z",
    "solution": "Fixed in [**8.2.0**](https://github.com/python-pillow/Pillow/releases/tag/8.2.0) by [this](https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92) commit.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.6
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2021-04-01T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1512",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-400"
            },
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-835"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2021-28677",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1512/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/pull/5377",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/releases/tag/8.2.0",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1512/default-remediation-status"
            }
        ]
    }
}