{
    "source": "BDSA",
    "name": "BDSA-2020-1714",
    "title": "Python Vulnerable to Code Injection via Improper Implementation of 'sys.path' Restrictions",
    "description": "Python is vulnerable to code injection due to `sys.path` restrictions being implemented incorrectly. This allows code to be loaded from arbitrary locations. \n\nThis issue only applies to Windows installations.",
    "technicalDescription": "Due to an error in the `get_pth_filename` function in `getpathp.c`, `sys.path` restrictions specified in a  `python38._pth` file are ignored allowing code to be loaded from arbitrary filesystem locations.",
    "publishedDate": "2020-07-17T13:34:03.079Z",
    "updatedDate": "2020-08-19T15:30:49.296Z",
    "disclosureDate": "2020-07-15T00:00:00.000Z",
    "exploitPublishDate": "2020-07-15T00:00:00.000Z",
    "solution": "Fixed in:\n* [**3.9.0-b5**](https://github.com/python/cpython/releases/tag/v3.9.0b5) by [this](https://github.com/python/cpython/commit/28e93dd2b26c460424acbebd00d8b943abbbea17) commit.\n* [**3.8.5**](https://github.com/python/cpython/releases/tag/v3.8.5) by [this](https://github.com/python/cpython/commit/3b6a8d2455c6897085f4277737b0f9b9a3847c24) commit.\n* [**3.7.9**](https://github.com/python/cpython/releases/tag/v3.7.9)  by [this](https://github.com/python/cpython/commit/4bfcffe16e9742c154f54ae96b5b36903500abaa) commit.\n\nThe latest stable releases are available [here](https://www.python.org/downloads/).",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 4.4,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 3.4,
        "severity": "LOW",
        "accessVector": "LOCAL",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.4
        },
        "vector": "(AV:L/AC:M/Au:N/C:P/I:P/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 8.6,
        "impactSubscore": 6.0,
        "exploitabilitySubscore": 1.8,
        "severity": "HIGH",
        "attackVector": "LOCAL",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "CHANGED",
        "userInteraction": "REQUIRED",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 7.7
        },
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "jgirardet",
    "workaround": "",
    "vendorFixDate": "2020-07-15T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 7.7,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1714",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-94"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-15801",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1714/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue41304",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue41304",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/28e93dd2b26c460424acbebd00d8b943abbbea17",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/3b6a8d2455c6897085f4277737b0f9b9a3847c24",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/4bfcffe16e9742c154f54ae96b5b36903500abaa",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/936a66094591dc0e67d4a60c170148bb700ec016",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/pull/21495",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.7.9",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.8.5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.9.0b5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://www.python.org/downloads/",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1714/default-remediation-status"
            }
        ]
    }
}