{
    "source": "BDSA",
    "name": "BDSA-2021-1282",
    "title": "Avahi Vulnerable to Denial-of-Service (DoS) via Reachable Assertion in 'avahi_s_host_name_resolver_start' Function",
    "description": "Avahi is vulnerable to a denial-of-service (DoS) issue due to the presence of a reachable assertion in the `avahi_s_host_name_resolver_start()` function.\n\nAn attacker could request invalid hostname resolutions in order to trigger the assertion and cause a crash of the Avahi service.",
    "technicalDescription": "Avahi is vulnerable to a denial-of-service (DoS) issue because the `avahi_s_host_name_resolver_start()` function in the `avahi-core/resolve-host-name.c` contains a reachable assertion. \n\nThis assertion can be triggered when a user passes an invalid hostname to the `RESOLVE-HOSTNAME` functionality in either `/run/avahi-daemon/socket` or through the `dbus` method `org.freedesktop.Avahi.Server.ResolveHostName`.\n\n**Note**: A third-party comment [here](https://bugzilla.redhat.com/show_bug.cgi?id=1946914#c5) states that this issue would result in a NULL pointer dereference even if assertions are compiled out.",
    "publishedDate": "2021-05-10T14:30:36.211Z",
    "updatedDate": "2022-03-28T11:45:55.838Z",
    "disclosureDate": "2021-03-27T00:00:00.000Z",
    "exploitPublishDate": "2021-03-27T00:00:00.000Z",
    "solution": "Fixed in the **master** branch by [this](https://github.com/lathiat/avahi/commit/fd482a74625b8db8547b8cfca3ee3d3c6c721423) commit which is not yet included in any release.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 2.1,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 3.9,
        "severity": "LOW",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 1.7
        },
        "vector": "(AV:L/AC:L/Au:N/C:N/I:N/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 6.2,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 2.5,
        "severity": "MEDIUM",
        "attackVector": "LOCAL",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.6
        },
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Thomas Kremer",
    "workaround": "",
    "vendorFixDate": "2021-06-04T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 5.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1282",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-617"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2021-3502",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1282/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986018",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986018",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://bugzilla.redhat.com/show_bug.cgi?id=1946914",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugzilla.redhat.com/show_bug.cgi?id=1946914#c5",
                "label": "LINK"
            },
            {
                "rel": "reference",
                "href": "https://github.com/lathiat/avahi/commit/80c98fa16782e921f5b5d5c880f1d80f5c43bd49",
                "label": "INTRODUCTORY_COMMIT"
            },
            {
                "rel": "reference",
                "href": "https://github.com/lathiat/avahi/commit/fd482a74625b8db8547b8cfca3ee3d3c6c721423",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/lathiat/avahi/issues/338",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/lathiat/avahi/pull/324",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-1282/default-remediation-status"
            }
        ]
    }
}