{
    "source": "BDSA",
    "name": "BDSA-2021-3825",
    "title": "NumPy Vulnerable to Denial-of-Service (DoS) via API Failure in 'numpy.core' Component",
    "description": "NumPy is vulnerable to denial-of-service (DoS) due to improper processing of string objects. An attacker could exploit this vulnerability by supplying an application with maliciously crafted input.",
    "technicalDescription": "The issue exists in the function `_convert_from_str()` within the file `numpy/core/src/multiarray/descriptor.c`. The vendor addressed this issue by removing functionality for deprecated numeric-style type codes.",
    "publishedDate": "2021-12-20T15:48:26.087Z",
    "updatedDate": "2021-12-20T15:48:26.073Z",
    "disclosureDate": "2021-05-12T00:00:00.000Z",
    "solution": "Fixed in **[1.22.0-rc1](https://github.com/numpy/numpy/releases/tag/v1.22.0rc1)** by [this](https://github.com/numpy/numpy/commit/eeef9d464) commit.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.6
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2021-08-11T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-3825",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-20"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2021-34141",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-3825/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/numpy/numpy/commit/eeef9d464",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/numpy/numpy/issues/18993",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/numpy/numpy/releases/tag/v1.22.0rc1",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-3825/default-remediation-status"
            }
        ]
    }
}