{
    "source": "BDSA",
    "name": "BDSA-2019-5134",
    "title": "PyCharm Vulnerable to Denial-of-Service via Excessive Memory Consumption During Connection Evaluation",
    "description": "PyCharm is vulnerable to denial-of-service (DoS) due to the uncontrolled allocation of memory. A remote attacker could cause a victim's instance of the application to crash by triggering an out-of-memory (OOM) exception.",
    "technicalDescription": "",
    "publishedDate": "2021-05-06T14:23:00.495Z",
    "updatedDate": "2021-11-08T14:17:58.841Z",
    "disclosureDate": "2019-09-26T00:00:00.000Z",
    "solution": "Fixed in [**2019.2**](https://www.jetbrains.com/pycharm/download/).",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 2.6,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 4.9,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 1.9
        },
        "vector": "(AV:N/AC:H/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.9,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 2.2,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.2
        },
        "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2019-07-23T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 5.2,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-5134",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-400"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2019-14958",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-5134/ranges"
            },
            {
                "rel": "reference",
                "href": "https://blog.jetbrains.com/blog/2019/09/26/jetbrains-security-bulletin-q2-2019/",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://www.jetbrains.com/pycharm/download/",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-5134/default-remediation-status"
            }
        ]
    }
}