{
    "source": "BDSA",
    "name": "BDSA-2015-0806",
    "title": "Python DLL Search Order Hijacking Vulnerability via Crafted 'readline.pyd' File",
    "description": "Python for Windows contains a DLL search order hijacking vulnerability.  This vulnerability allows an attacker to execute code on a system by placing a crafted file in a directory where `Python.exe` is being called from. \n\n**Note:** \n* Only Windows systems are vulnerable. \n* The vendor states:\n>\"It was determined that this is a longtime behavior of Python that cannot really be altered at this point.\"",
    "technicalDescription": "Python uses an insecure method for loading DLLs.  A crafted file named `readline.pyd` can be placed in the current directory that may result in the execution of code when a user calls `Python.exe`. This issue was resolved for python running in isolate mode (`python -I`), but users are still vulnerable when running python in interactive mode.",
    "publishedDate": "2021-04-26T09:15:24.687Z",
    "updatedDate": "2021-09-28T11:59:21.248Z",
    "disclosureDate": "2015-10-01T00:00:00.000Z",
    "solution": "",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 6.8,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 8.6,
        "severity": "MEDIUM",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "WORKAROUND",
            "reportConfidence": "CONFIRMED",
            "score": 5.5
        },
        "vector": "(AV:N/AC:M/Au:N/C:P/I:P/A:P/E:U/RL:W/RC:C)"
    },
    "cvss3": {
        "baseScore": 8.8,
        "impactSubscore": 5.9,
        "exploitabilitySubscore": 2.8,
        "severity": "HIGH",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "REQUIRED",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "WORKAROUND",
            "reportConfidence": "CONFIRMED",
            "score": 7.8
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H/E:U/RL:W/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Takashi Yoshikawa",
    "workaround": "Resolved for isolate mode only in [**3.6**]() with [this](https://hg.python.org/cpython/rev/b0350f351752) commit. \n\n[According to the vendor](https://bugs.python.org/issue12238), to prevent Python from important files from either cwd, user packages or env vars,  isolated mode should be used. System scripts should use isolated mode.",
    "bdsaTags": [
        "RCE"
    ],
    "overallScore": 7.8,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2015-0806",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-426"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2015-5652",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2015-0806/ranges"
            },
            {
                "rel": "reference",
                "href": "http://jvn.jp/en//jp/JVN49503705/",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue12238",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue12238",
                "label": "WORKAROUND"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue25288",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://hg.python.org/cpython/rev/b0350f351752",
                "label": "PATCH"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2015-0806/default-remediation-status"
            }
        ]
    }
}