{
    "source": "BDSA",
    "name": "BDSA-2017-4064",
    "title": "Python Vulnerable to Denial-of-Service (DoS) via Divide-by-Zero via Crafted Wav File",
    "description": "Python contains a divide-by-zero vulnerability. An attacker could exploit this by supplying a crafted `.wav` file in order to cause a denial-of-service (DoS) condition. \n\nThe Vendor disputes the validity of this issue, stating \"if an application is vulnerable to a denial-of-service attack due to a faulty `.wav` file, it is a failure in that application to be handling possible exceptions from `wave.py`, not a security issue in Python itself.\".",
    "technicalDescription": "This issue affects the `Wave_read._read_fmt_chunk()` function of the `Lib/wave.py` file because of improper checks relating to nonzero channel values. It was mitigated by improving the exceptions raised within `Lib/wave.py`",
    "publishedDate": "2021-06-30T11:51:22.498Z",
    "updatedDate": "2021-06-30T11:51:22.491Z",
    "disclosureDate": "2017-11-17T00:00:00.000Z",
    "exploitPublishDate": "2017-11-17T00:00:00.000Z",
    "solution": "Fixed in [**3.7.0b3**](https://github.com/python/cpython/releases/tag/v3.7.0b3) by [this](https://github.com/python/cpython/commit/3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371) commit.\n\nThe latest stable releases are available [here](https://github.com/python/cpython/releases).",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 4.3,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 8.6,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.4
        },
        "vector": "(AV:N/AC:M/Au:N/C:N/I:N/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 6.5,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 2.8,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "REQUIRED",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.9
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "zhangdeyue",
    "workaround": "",
    "vendorFixDate": "2018-03-18T00:00:00.000Z",
    "vendorNotifiedDate": "2017-11-17T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 5.9,
    "_meta": {
        "allow": [],
        "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2017-4064",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-369"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/CVE-2017-18207",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2017-4064/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue32056",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue32056",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.7.0b3",
                "label": "VENDOR_UPGRADE"
            }
        ]
    }
}