{
    "source": "BDSA",
    "name": "BDSA-2022-1913",
    "title": "XNIO Vulnerable to Denial-of-Service (DoS) via Allocation of Resources Without Limits in the 'notifyReadClosed' Method",
    "description": "XNIO is vulnerable to denial-of-service (DoS) due to allocation of resources without limits within the `notifyReadClosed` method. An attacker could exploit this by sending flawed requests to a server, in order to cause log contention-related performance concerns or an unwanted disk fill-up.",
    "technicalDescription": "This issue occurs in the `api/src/main/java/org/xnio/StreamConnection.java` file. It was mitigated by ensuring that stack traces are not printed and the logger is utilized instead.",
    "publishedDate": "2022-07-12T09:39:20.350Z",
    "updatedDate": "2022-07-12T09:39:20.342Z",
    "disclosureDate": "2022-03-15T00:00:00.000Z",
    "solution": "Fixed in the **3.x** branch by [this](https://github.com/xnio/xnio/commit/b05531de0433f498af26f9aec6c0e944c3c1689c) commit which is not yet included in any release.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 2.6,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 4.9,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 1.9
        },
        "vector": "(AV:N/AC:H/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.9,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 2.2,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.2
        },
        "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": true,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2022-05-26T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 5.2,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2022-1913",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-770"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2022-0084",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2022-1913/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugzilla.redhat.com/show_bug.cgi?id=2064226",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/xnio/xnio/commit/b05531de0433f498af26f9aec6c0e944c3c1689c",
                "label": "PATCH"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2022-1913/default-remediation-status"
            }
        ]
    }
}