{
    "source": "BDSA",
    "name": "BDSA-2020-3345",
    "title": "python-rsa Vulnerable to Information Exposure via Bleichenbacher Timing Attacks",
    "description": "python-rsa is vulnerable to information exposure due to weaknesses in processing of PKCS#1 v**1.5** ciphertext, which may allow adaptive chosen-ciphertext (Bleichenbacher) attacks. This could allow an attacker to deduce sensitive information from RSA-encrypted ciphertext using the RSA decryption API.",
    "technicalDescription": "The issue exists with PKCS#1 v**1.5** decryption within the file `rsa/pkcs1.py`. Improper handling of exception raising could expose a timing side channel which allows an attacker to determine the execution path when errors occur, which in turn could be leveraged to recover plaintext from RSA-encrypted data. It was mitigated by the implementation of constant-time comparisons in the\n`decrypt()` function of the `rsa/pkcs1.py` .",
    "publishedDate": "2020-11-13T16:30:53.933Z",
    "updatedDate": "2021-03-04T11:27:46.887Z",
    "disclosureDate": "2020-10-26T00:00:00.000Z",
    "solution": "Fixed in [**4.7**](https://github.com/sybrenstuvel/python-rsa/releases/tag/version-4.7) by [this](https://github.com/sybrenstuvel/python-rsa/commit/dae8ce0d85478e16f2368b2341632775313d41ed) commit.\n\nThe latest stable releases are available [here](https://github.com/sybrenstuvel/python-rsa/releases).",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:P/I:N/A:N/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 7.5,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 6.5
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Hubert Kario",
    "workaround": "",
    "vendorFixDate": "2020-11-15T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 6.5,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3345",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-208"
            },
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-310"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-25658",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3345/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/sybrenstuvel/python-rsa/commit/714324a9a34f0958704e5064251a1f00ed37a372",
                "label": "INTRODUCTORY_COMMIT"
            },
            {
                "rel": "reference",
                "href": "https://github.com/sybrenstuvel/python-rsa/commit/dae8ce0d85478e16f2368b2341632775313d41ed",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/sybrenstuvel/python-rsa/issues/165",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/sybrenstuvel/python-rsa/releases",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/sybrenstuvel/python-rsa/releases/tag/version-4.7",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3345/default-remediation-status"
            }
        ]
    }
}