{
    "source": "BDSA",
    "name": "BDSA-2020-0547",
    "title": "Keycloak Vulnerable to Brute Force Protection Bypass via Capture Failure of Failed Login Attempts",
    "description": "Keycloak is vulnerable to a flaw whereby it fails to capture failed login attempts. A remote attacker could bypass the brute force protection mechanism.",
    "technicalDescription": "With conditional OTP authentication flow as a post login flow of an IDP, failed logins were not being passed to the `BruteForceProtector`.",
    "publishedDate": "2020-03-26T16:02:43.861Z",
    "updatedDate": "2021-08-24T15:57:38.982Z",
    "disclosureDate": "2020-02-21T00:00:00.000Z",
    "solution": "Fixed in [**9.0.2**](https://github.com/keycloak/keycloak/releases/tag/9.0.2) by [this](https://github.com/keycloak/keycloak/commit/9474dd6208c01166b6144bea3ac2b6fe9f5c30f4) commit.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.1,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 4.9,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.8
        },
        "vector": "(AV:N/AC:H/Au:N/C:P/I:P/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.6,
        "impactSubscore": 3.4,
        "exploitabilitySubscore": 2.2,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "HIGH",
        "confidentialityImpact": "LOW",
        "integrityImpact": "LOW",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.9
        },
        "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2020-02-19T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.9,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-0547",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-693"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-1744",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-0547/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugzilla.redhat.com/show_bug.cgi?id=1805792",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/keycloak/keycloak/commit/9474dd6208c01166b6144bea3ac2b6fe9f5c30f4",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/keycloak/keycloak/releases/tag/9.0.2",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://issues.redhat.com/browse/KEYCLOAK-12986",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-0547/default-remediation-status"
            }
        ]
    }
}