{
    "source": "BDSA",
    "name": "BDSA-2021-0034",
    "title": "Pillow Vulnerable to Denial-of-Service (DoS) via Out-of-Bounds Write in 'TiffDecode.c' File",
    "description": "Pillow is vulnerable to a denial-of-service (DoS) condition due to an out-of-bounds (OOB) write issue present in the `TiffDecode.c` file.\n\nAn attacker could supply a crafted file in order to negatively impact the stability of Pillow and potentially cause a crash.",
    "technicalDescription": "Pillow is vulnerable to a denial-of-service (DoS) condition because of an out-of-bounds (OOB) write error in the `src/libImaging/TiffDecode.c` file, which can occur during read operations on corrupt YCbCr files when using certain LibTIFF versions. \n\n**Note**: Certain versions of LibTIFF can interpret YCbCr files differently when reading in RGBA mode. This issue can manifest for at least LibTIFF version 4.1.0 (as used with Ubuntu 20.04), but not for LibTIFF 4.0.9 (as used with Ubuntu 18.04).\n\n**Note**: The fixes applied in version [**8.1.0**](https://github.com/python-pillow/Pillow/releases/tag/8.1.0) by [this](https://github.com/python-pillow/Pillow/commit/c8dd1c84220c11f4e9ab12a166c0da91adace94a) commit are insufficient as they still allow a buffer overflow to occur. Subsequently, **CVE-2021-25289** (**BDSA-2021-0518**) was assigned afterwards and further fixes were applied in **8.1.1**.",
    "publishedDate": "2021-01-12T14:25:21.223Z",
    "updatedDate": "2021-08-11T11:40:20.948Z",
    "disclosureDate": "2021-01-02T00:00:00.000Z",
    "solution": "Fixed in [**8.1.1**](https://github.com/python-pillow/Pillow/releases/tag/8.1.1) by [this](https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299) commit.\n\nThe latest stable releases are available [here](https://github.com/python-pillow/Pillow/releases).",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.6
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2021-01-02T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-0034",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-787"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-35654",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-0034/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/commit/c8dd1c84220c11f4e9ab12a166c0da91adace94a",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299)",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/pull/5175",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/releases",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/releases/tag/8.1.0",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python-pillow/Pillow/releases/tag/8.1.1",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2021-0034/default-remediation-status"
            }
        ]
    }
}