{
    "source": "BDSA",
    "name": "BDSA-2018-4454",
    "title": "libarchive Vulnerable to Denial-of-Service via Specially Crafted bsdtar Input",
    "description": "An attacker who can supply a specially crafted tar file to an application linking against libarchive can cause a denial-of-service (*DoS*) of the application.",
    "technicalDescription": "A tar archive with a specially crafted 0-length ACL field will cause a Null pointer in libarchives bsdtar handling.  This will cause the linked application to crash, resulting in a denial-of-service (*DoS*).",
    "publishedDate": "2018-12-21T12:08:57.487Z",
    "updatedDate": "2018-12-21T12:08:57.470Z",
    "disclosureDate": "2018-12-04T00:00:00.000Z",
    "solution": "Fixed by [this](https://github.com/libarchive/libarchive/pull/1105/commits/15bf44fd2c1ad0e3fd87048b3fcc90c4dcff1175) git commit which is not yet part of any stable release.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 6.2,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 2.5,
        "severity": "MEDIUM",
        "attackVector": "LOCAL",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.4
        },
        "vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": true,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2018-12-04T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 5.4,
    "_meta": {
        "allow": [],
        "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2018-4454",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-476"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/CVE-2018-1000879",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2018-4454/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/libarchive/libarchive/pull/1105",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/libarchive/libarchive/pull/1105/commits/15bf44fd2c1ad0e3fd87048b3fcc90c4dcff1175",
                "label": "PATCH"
            }
        ]
    }
}