{
    "source": "BDSA",
    "name": "BDSA-2015-0814",
    "title": "Python Vulnerable to Remote Code Execution (RCE) via Command Injection in 'mailcap' Module",
    "description": "Python is vulnerable to remote code execution due to the insufficient sanitization of untrusted input in its `mailcap` module. An attacker could execute arbitrary commands on a vulnerable host by causing the module to process a maliciously crafted filename.\n\n**Note**: An application must pass untrusted input to the `findmatch()` function, via the `filename` parameter, in order for the vulnerability to manifest.",
    "technicalDescription": "The `findmatch()` function, of file `Lib/mailcap.py` is used by the `mailcap` Python module in order to perform file system operations. One of the parameters of this function is `filename`. The function performs insufficient sanitization on the value of `filename`, which is used to dynamically construct a command which will be executed by `os.system()`. An attacker that is able to control the value of `filename` could potentially leverage this issue in order to execute arbitrary commands on the system.\n\n**Note**: An application must pass untrusted input to the `findmatch()` function, via the `filename` parameter, in order for the vulnerability to manifest.",
    "publishedDate": "2022-04-14T16:15:18.700Z",
    "updatedDate": "2022-04-14T16:15:18.681Z",
    "disclosureDate": "2015-08-02T00:00:00.000Z",
    "exploitPublishDate": "2015-08-02T00:00:00.000Z",
    "solution": "",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 5.1,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 4.9,
        "severity": "MEDIUM",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "UNAVAILABLE",
            "reportConfidence": "CONFIRMED",
            "score": 4.6
        },
        "vector": "(AV:N/AC:H/Au:N/C:P/I:P/A:P/E:POC/RL:U/RC:C)"
    },
    "cvss3": {
        "baseScore": 8.1,
        "impactSubscore": 5.9,
        "exploitabilitySubscore": 2.2,
        "severity": "HIGH",
        "attackVector": "NETWORK",
        "attackComplexity": "HIGH",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "UNAVAILABLE",
            "reportConfidence": "CONFIRMED",
            "score": 7.7
        },
        "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H/E:P/RL:U/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "bdsaTags": [
        "RCE"
    ],
    "overallScore": 7.7,
    "_meta": {
        "allow": [],
        "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2015-0814",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-78"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/CVE-2015-20107",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2015-0814/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue24778",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/issues/68966",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/issues/68966",
                "label": "POC"
            }
        ]
    }
}